--liquibase formatted sql

--changeset siftnews:0001-create-application-schema
CREATE TABLE source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    lang VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    last_crawled_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_source_url UNIQUE (url)
);

CREATE TABLE article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    source_id BIGINT NOT NULL,
    url VARCHAR(2048) NOT NULL,
    normalized_url VARCHAR(2048) NOT NULL,
    title VARCHAR(1024),
    body TEXT,
    lang VARCHAR(16),
    published_at TIMESTAMP(6) WITH TIME ZONE,
    category VARCHAR(255),
    dedup_cluster_id VARCHAR(64),
    CONSTRAINT uk_article_normalized_url UNIQUE (normalized_url)
);

CREATE TABLE topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    lang_scope VARCHAR(255) NOT NULL,
    include_keywords JSONB NOT NULL,
    exclude_keywords JSONB NOT NULL,
    keyword_weights JSONB NOT NULL,
    source_categories JSONB NOT NULL,
    recency_half_life_hours INTEGER NOT NULL,
    max_items INTEGER NOT NULL,
    score_threshold DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_topic_slug UNIQUE (slug)
);

CREATE TABLE article_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    article_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    breakdown JSONB NOT NULL,
    computed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_article_score_article_topic UNIQUE (article_id, topic_id)
);

CREATE TABLE issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    topic_id BIGINT NOT NULL,
    run_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    scheduled_at TIMESTAMP(6) WITH TIME ZONE,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_issue_topic_run_date UNIQUE (topic_id, run_date)
);

CREATE TABLE issue_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    issue_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    item_rank INTEGER NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    CONSTRAINT uk_issue_item_issue_article UNIQUE (issue_id, article_id)
);

-- Spring Modulith의 외부화 이벤트 영속소. 기본 완료 모드(update)가 사용하는 테이블이다.
CREATE TABLE event_publication (
    id UUID NOT NULL PRIMARY KEY,
    publication_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    listener_id VARCHAR(255) NOT NULL,
    serialized_event VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    completion_date TIMESTAMP(6) WITH TIME ZONE
);
