--liquibase formatted sql

--changeset siftnews:0004-create-subscriber-schema
CREATE TABLE subscriber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    email VARCHAR(320) NOT NULL,
    status VARCHAR(32) NOT NULL,
    preferred_send_hour INTEGER NOT NULL,
    CONSTRAINT uk_subscriber_email UNIQUE (email),
    CONSTRAINT ck_subscriber_preferred_send_hour CHECK (preferred_send_hour BETWEEN 0 AND 23)
);

CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    subscriber_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT uk_subscription_subscriber_topic UNIQUE (subscriber_id, topic_id),
    CONSTRAINT fk_subscription_subscriber FOREIGN KEY (subscriber_id) REFERENCES subscriber (id),
    CONSTRAINT fk_subscription_topic FOREIGN KEY (topic_id) REFERENCES topic (id)
);

CREATE INDEX idx_subscriber_status_send_hour ON subscriber (status, preferred_send_hour);
CREATE INDEX idx_subscription_topic_status ON subscription (topic_id, status);
