--liquibase formatted sql

--changeset siftnews:0005-create-delivery-schema
CREATE TABLE delivery_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    issue_id BIGINT NOT NULL,
    total_count INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT uk_delivery_job_issue UNIQUE (issue_id),
    CONSTRAINT fk_delivery_job_issue FOREIGN KEY (issue_id) REFERENCES issue (id)
);

CREATE TABLE delivery_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    delivery_job_id BIGINT NOT NULL,
    subscriber_id BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP(6) WITH TIME ZONE,
    last_error TEXT,
    sent_at TIMESTAMP(6) WITH TIME ZONE,
    idempotency_key VARCHAR(64) NOT NULL,
    CONSTRAINT uk_delivery_task_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_delivery_task_job FOREIGN KEY (delivery_job_id) REFERENCES delivery_job (id),
    CONSTRAINT fk_delivery_task_subscriber FOREIGN KEY (subscriber_id) REFERENCES subscriber (id)
);

CREATE INDEX idx_delivery_task_status_retry ON delivery_task (status, next_retry_at);
